# Ensemble Technique
## Bagging
### Random Forest 

* Hyperparameter Tuning(Grid Search And RandomSearch)
* Decsion tree have low bias and high variance
* Therefore use randon forest to get low bias and low variance

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # for data visualization purposes
import seaborn as sns # for statistical data visualization
%matplotlib inline

In [2]:
df=pd.read_csv('F:/GitHub/Machine-Learning/Ensemble_Bagging_Random Forest/winequality-red.csv')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [8]:
#separate features and target
X=df.drop(['quality'],axis=1)
y=df['quality']

In [9]:
#Separate test and train
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=27)
X_train.shape, X_test.shape

((1199, 11), (400, 11))

In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
clf = RandomForestClassifier(max_depth=5, random_state=0)
clf.fit(X_train, y_train)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=5, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [14]:
y_pred=clf.predict(X_test)

In [15]:
#confusion matrix
from sklearn.metrics import confusion_matrix
print (confusion_matrix(y_test, y_pred))

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

[[  0   0   3   0   0   0]
 [  0   0   1   3   0   0]
 [  0   0 137  28   0   0]
 [  0   0  59 106   1   0]
 [  0   0   1  44  11   0]
 [  0   0   0   6   0   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00         4
           5       0.68      0.83      0.75       165
           6       0.57      0.64      0.60       166
           7       0.92      0.20      0.32        56
           8       0.00      0.00      0.00         6

    accuracy                           0.64       400
   macro avg       0.36      0.28      0.28       400
weighted avg       0.64      0.64      0.60       400



c:\users\manzoor\anaconda3\envs\venv\lib\site-packages\sklearn\metrics\_classification.py:1268: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
